[package]
name = "yolo-rust-inference"
version = "0.1.0"
edition = "2021"

[dependencies]
onnxruntime = "0.10.0"
image = "0.23.14"
ndarray = "0.15.3"
ndarray-rand = "0.14.0"
opencv = { version = "0.66", features = ["opencv-4"] }
anyhow = "1.0"